<a href="https://colab.research.google.com/github/JotaDC/TPI-Data-Analytics-TalentoTech/blob/main/Ca%C3%B1ete_Javier_Dario_Comisi%C3%B3n_25261_TPI_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pre-Entrega del proyecto integrador**

  *   Curso: Data Analitics con Python
  *   Comision: 25261
  *   Alumno: Javier Dario Cañete
  *   Fecha: 14-10-2025

  **Objetivo**: Demostrar habilidades en Python, familiaridad con el entorno de trabajo y conocimientos básicos sobre manipulación de datos asi como demostrar conocimiento de las técnicas de limpieza y transformación de datos.


##**Etapa 1: Recopilación y Preparación de Datos (Clases 1 a 4)**


###**1. Crear un documento Google Colaboratory y cargar los set de datos como DataFrames.**

In [200]:
#Importar los librerias
import pandas as pd
import numpy as np
#Cargar los Dataframes con los set de datos
df_ventas=pd.read_csv('ventas.csv')
df_clientes=pd.read_csv('clientes.csv')
df_marketing=pd.read_csv('marketing.csv')


###**2. Realizar un script básico que calcule las ventas mensuales utilizando variables y operadores.**

In [201]:
# Abrir el archivo CSV
with open('ventas.csv', 'r', encoding='utf-8') as archivo:
    lineas = archivo.readlines()

# Quitar el encabezado
lineas = lineas[1:]

# Diccionario para acumular las ventas por mes
ventas_mensuales = {}

# Recorrer cada línea
for linea in lineas:
    linea = linea.strip()
    if not linea:  # Saltar líneas vacías
        continue

    partes = linea.split(',')

    # Asegurar que tenga al menos 6 columnas
    if len(partes) < 6:
        continue

    id_venta = partes[0].strip()
    producto = partes[1].strip()
    precio_str = partes[2].strip()
    cantidad_str = partes[3].strip()
    fecha_venta = partes[4].strip()
    categoria = partes[5].strip()

    # Limpiar y validar precio
    precio_str = precio_str.replace('$', '')
    #.replace(' ', '').replace('.', '').replace(',', '.')
    if not precio_str:
        continue  # si está vacío, salteamos
    try:
        precio = float(precio_str)
    except ValueError:
        continue  # si no se puede convertir, se salta

    # Validar cantidad
    if not cantidad_str.isdigit():
        continue
    cantidad = int(cantidad_str)

    # Calcular total
    total_venta = precio * cantidad

    # Obtener mes de la fecha (DD/MM/YYYY)
    if len(fecha_venta) >= 5:
        mes = fecha_venta[3:5]
    else:
        continue  # si la fecha no tiene formato válido

    # Acumular
    if mes in ventas_mensuales:
        ventas_mensuales[mes] += total_venta
    else:
        ventas_mensuales[mes] = total_venta

# Mostrar resultados
total_general=0
print("=== Ventas mensuales ===")
for mes, total in ventas_mensuales.items():
    print(f"Mes {mes}: ${total:,.2f}")
    total_general=total_general+total
print(f"Total general de ventas: ${total_general:,.2f}")


=== Ventas mensuales ===
Mes 01: $129,604.99
Mes 02: $118,672.44
Mes 03: $136,779.15
Mes 04: $144,380.10
Mes 05: $143,727.25
Mes 06: $108,480.17
Mes 07: $116,229.97
Mes 08: $119,680.15
Mes 09: $115,787.85
Mes 10: $112,117.13
Mes 11: $119,951.79
Mes 12: $117,631.94
Total general de ventas: $1,483,042.93


###**3. Estructuras de Datos: Desarrollar un programa que almacene los datos de ventas (producto, precio, cantidad). Decidir si conviene utilizar diccionarios o listas.**

In [202]:
# Estructuras de datos: Lista de diccionarios (Me parece que genera un codigo mas legible)

ventas = []  # lista vacía para almacenar las ventas

# Abrir el archivo CSV
with open('ventas.csv', 'r', encoding='utf-8') as archivo:
    lineas = archivo.readlines()

# Quitar el encabezado
lineas = lineas[1:]

# Diccionario para acumular las ventas por mes
ventas_mensuales = {}

# Recorrer cada línea
for linea in lineas:
    linea = linea.strip()
    if not linea:  # Saltar líneas vacías
        continue

    partes = linea.split(',')

    # Asegurar que tenga al menos 6 columnas
    if len(partes) < 6:
        continue

    id_venta = partes[0].strip()
    producto = partes[1].strip()
    precio_str = partes[2].strip()
    cantidad_str = partes[3].strip()
    fecha_venta = partes[4].strip()
    categoria = partes[5].strip()

    # Limpiar y validar precio
    precio_str = precio_str.replace('$', '').replace(' ', '').replace('.', '').replace(',', '.')
    if not precio_str:
        continue  # si está vacío, salteamos
    try:
        precio = float(precio_str)
    except ValueError:
        continue  # si no se puede convertir, se salta

    # Validar cantidad
    if not cantidad_str.isdigit():
        continue
    cantidad = int(cantidad_str)

    # Calcular total
    total_venta = precio * cantidad

    # Obtener mes de la fecha (DD/MM/YYYY)
    if len(fecha_venta) >= 5:
        mes = fecha_venta[3:5]
    else:
        continue  # si la fecha no tiene formato válido

    # Acumular
    if mes in ventas_mensuales:
        ventas_mensuales[mes] += total_venta
    else:
        ventas_mensuales[mes] = total_venta
 # Crear el diccionario para esta venta
    venta = {
        "producto": producto,
        "precio": precio,
        "cantidad": cantidad
    }

    # Agregarlo a la lista
    ventas.append(venta)

# Mostrar todas las ventas almacenadas
total_general=0
print("=== Ventas registradas ===")
for venta in ventas:
    total = venta["precio"] * venta["cantidad"]
    print(f"Producto: {venta['producto']}, Precio: ${venta['precio']:,.2f}, Cantidad: {venta['cantidad']}, Total: ${total:,.2f}")
    # Calcular el total general
    total_general += total

# Mostrar el total general
print(f"\nTotal general de ventas: ${total_general:,.2f}")


=== Ventas registradas ===
Producto: Cuadro decorativo, Precio: $6,994.00, Cantidad: 5, Total: $34,970.00
Producto: Lámpara de mesa, Precio: $10,510.00, Cantidad: 5, Total: $52,550.00
Producto: Secadora, Precio: $9,796.00, Cantidad: 3, Total: $29,388.00
Producto: Heladera, Precio: $11,435.00, Cantidad: 8, Total: $91,480.00
Producto: Secadora, Precio: $10,621.00, Cantidad: 4, Total: $42,484.00
Producto: Horno eléctrico, Precio: $3,535.00, Cantidad: 9, Total: $31,815.00
Producto: Plancha de vapor, Precio: $6,543.00, Cantidad: 2, Total: $13,086.00
Producto: Proyector, Precio: $8,817.00, Cantidad: 9, Total: $79,353.00
Producto: Rincón de plantas, Precio: $7,986.00, Cantidad: 11, Total: $87,846.00
Producto: Candelabro, Precio: $6,611.00, Cantidad: 8, Total: $52,888.00
Producto: Aspiradora, Precio: $9,590.00, Cantidad: 5, Total: $47,950.00
Producto: Freidora eléctrica, Precio: $11,118.00, Cantidad: 1, Total: $11,118.00
Producto: Aspiradora, Precio: $7,091.00, Cantidad: 2, Total: $14,182.00
P

###**4. Introducción a Pandas: Realizar un análisis exploratorio inicial de los DataFrames.**

In [203]:
def exploracion_inicial(df,titulo):
    print("="*50)
    print(f"=== Información de DataFrame {titulo}===")
    print("="*50)
    print(f"Cantidad de Registros:{df.shape[0]}")
    print(f"Cantidad de Columnas:{df.shape[1]}")
    print()
    print("Informacion de las columnas, nulos y tipos  de datos")
    print("-"*50)
    print(df.info())
    print()
    print("Listado de los primeros 5 registros")
    print("-"*50)
    print(df.head())
    print()
    print("Listado de los ultimos 5 registros")
    print("-"*50)
    print(df.tail())
    print()
    print("Estadisticas descriptivas")
    print("-"*50)
    print(df.describe())
    print()
    print()


In [204]:
exploracion_inicial(df_ventas,"Ventas")

=== Información de DataFrame Ventas===
Cantidad de Registros:3035
Cantidad de Columnas:6

Informacion de las columnas, nulos y tipos  de datos
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id_venta     3035 non-null   int64  
 1   producto     3035 non-null   object 
 2   precio       3033 non-null   object 
 3   cantidad     3033 non-null   float64
 4   fecha_venta  3035 non-null   object 
 5   categoria    3035 non-null   object 
dtypes: float64(1), int64(1), object(4)
memory usage: 142.4+ KB
None

Listado de los primeros 5 registros
--------------------------------------------------
   id_venta           producto   precio  cantidad fecha_venta  \
0       792  Cuadro decorativo   $69.94       5.0  02/01/2024   
1       811    Lámpara de mesa  $105.10       5.0  02/01/2024   
2      1156 

In [205]:
exploracion_inicial(df_clientes,"Clientes")

=== Información de DataFrame Clientes===
Cantidad de Registros:567
Cantidad de Columnas:5

Informacion de las columnas, nulos y tipos  de datos
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id_cliente  567 non-null    int64  
 1   nombre      567 non-null    object 
 2   edad        567 non-null    int64  
 3   ciudad      567 non-null    object 
 4   ingresos    567 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 22.3+ KB
None

Listado de los primeros 5 registros
--------------------------------------------------
   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  357

In [206]:
exploracion_inicial(df_marketing,"Marketing")

=== Información de DataFrame Marketing===
Cantidad de Registros:90
Cantidad de Columnas:6

Informacion de las columnas, nulos y tipos  de datos
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id_campanha   90 non-null     int64  
 1   producto      90 non-null     object 
 2   canal         90 non-null     object 
 3   costo         90 non-null     float64
 4   fecha_inicio  90 non-null     object 
 5   fecha_fin     90 non-null     object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.3+ KB
None

Listado de los primeros 5 registros
--------------------------------------------------
   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13

**Obsevaciones de los DataFrames:**

**Ventas**: El precio y la fecha son de tipo Object y se deberia cambiar a float y formato fecha respectivamente.
En precio y cantidad hay 2 nulos.

**Marketing**: las fecha_inicio y fecha_final pasar a formato fecha.


###**5. Calidad de Datos: Identificar valores nulos y duplicados en los conjuntos de datos. Documentar el estado inicial de los datos.**

In [207]:
print("\n=== VALORES NULOS ===")
print("\nVentas:")
print(df_ventas.isnull().sum())

print("\nClientes:")
print(df_clientes.isnull().sum())

print("\nMarketing:")
print(df_marketing.isnull().sum())

# === 5. Verificar duplicados ===
print("\n=== DUPLICADOS ===")

print(f"Ventas duplicadas: {df_ventas.duplicated(keep='first').sum()}")
print(f"Clientes duplicados: {df_clientes.duplicated(keep='first').sum()}")
print(f"Marketing duplicados: {df_marketing.duplicated(keep='first').sum()}")


=== VALORES NULOS ===

Ventas:
id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64

Clientes:
id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64

Marketing:
id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64

=== DUPLICADOS ===
Ventas duplicadas: 35
Clientes duplicados: 0
Marketing duplicados: 0


**Estado Inicial de los datos:**
```
**=== VALORES NULOS ===**
Ventas: En precio y cantidad hay 2 nulos
Clientes: No hay nulos
Marketing: No hay nulos

**=== DUPLICADOS ===**
Ventas duplicadas: 35
Clientes duplicados: 0
Marketing duplicados: 0
```







##**Etapa 2: Preprocesamiento y Limpieza de Datos (Clases 5 a 8)**

###**1- Limpieza de Datos: Limpiar el conjunto de datos eliminando duplicados y caracteres no deseados. Documentar el proceso y los resultados.**

####Quitar Nulos

In [208]:
#Quitar elementos Nulos de Ventas

#Guardar las filas con valores nulos
df_ventas_nulos = df_ventas[df_ventas.isna().any(axis=1)]

#Eliminar las filas nulas del DataFrame original
df_ventas = df_ventas.dropna()

print("Registros Eliminados por tener Nulos")
display(df_ventas_nulos)

Registros Eliminados por tener Nulos


id_venta               producto precio  cantidad fecha_venta    categoria
136       627  Elementos de cerámica    NaN       NaN  17/01/2024   Decoración
139      2171    Parlantes Bluetooth    NaN       NaN  17/01/2024  Electrónica

**Registros Eliminados por tener Nulos**
```
id_venta	producto	precio	cantidad	fecha_venta	categoria
136	627	Elementos de cerámica	NaN	NaN	17/01/2024	Decoración
139	2171	Parlantes Bluetooth	NaN	NaN	17/01/2024	Electrónica
```

####Quitar caracteres no deseados y convertir a lo tipos correctos

In [214]:
#Quitar caracteres no deseados del precio y convertir a tipo float
df_ventas['precio'] = df_ventas['precio'].replace(r'[\$,]', '', regex=True).astype(float)

#Quitar espacios al inicio y al final de producto y categoria
df_ventas['producto'] = df_ventas['producto'].str.strip()
df_ventas['categoria'] = df_ventas['categoria'].str.strip()

#Convertir fecha_venta a tipo datetime
df_ventas['fecha_venta'] = pd.to_datetime(df_ventas['fecha_venta'], dayfirst=True, errors='coerce')

#Mostrar cantidad de registros sin convertir y como quedo df_ventas con los cambios de tipo de dato.
print(f"Registros sin poder convertirse a datetime = {df_ventas['fecha_venta'].isna().sum()}")
df_ventas.info()


Registros sin poder convertirse a datetime = 0
<class 'pandas.core.frame.DataFrame'>
Index: 2998 entries, 0 to 3034
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   id_venta     2998 non-null   int64         
 1   producto     2998 non-null   object        
 2   precio       2998 non-null   float64       
 3   cantidad     2998 non-null   float64       
 4   fecha_venta  2998 non-null   datetime64[ns]
 5   categoria    2998 non-null   object        
 6   total_venta  2998 non-null   float64       
 7   año_mes      2998 non-null   period[M]     
dtypes: datetime64[ns](1), float64(3), int64(1), object(2), period[M](1)
memory usage: 210.8+ KB


####Quitar Duplicados

In [210]:
#Mostrar elementos a eliminar por se duplicado
print(f"Total de duplicados eliminados = {df_ventas.duplicated(keep='first').sum()}")

#Eliminar los duplicados del DataFrame original
df_ventas = df_ventas.drop_duplicates(keep="first")

#Mostrar el DataFrame sin duplicados
print("DataFrame sin duplicados")
display(df_ventas)


Total de duplicados eliminados = 35
DataFrame sin duplicados


id_venta                producto  precio  cantidad fecha_venta  \
0          792       Cuadro decorativo   69.94       5.0  2024-01-02   
1          811         Lámpara de mesa  105.10       5.0  2024-01-02   
2         1156                Secadora   97.96       3.0  2024-01-02   
3         1372                Heladera  114.35       8.0  2024-01-02   
4         1546                Secadora  106.21       4.0  2024-01-02   
...        ...                     ...     ...       ...         ...   
3030      1837         Horno eléctrico  104.12       9.0  2024-12-30   
3031      2276                  Laptop   85.27       9.0  2024-12-30   
3032      2696                  Laptop  107.81       4.0  2024-12-30   
3033      2913              Smartphone   99.85       7.0  2024-12-30   
3034      2930  Consola de videojuegos   55.47       6.0  2024-12-30   

              categoria  
0            Decoración  
1            Decoración  
2     Electrodomésticos  
3     Electrodomésticos  
4     Electrodomésticos  
...                 ...  
3030  Electrodomésticos  
3031        Electrónica  
3032        Electrónica  
3033        Electrónica  
3034        Electrónica  

[2998 rows x 6 columns]

###**2- Transformación de Datos: Aplicar filtros y transformaciones para crear una tabla de ventas que muestre solo los productos con alto rendimiento.**

In [220]:
#Crear una columna con el total de cada venta
df_ventas['total_venta'] = df_ventas['precio'] * df_ventas['cantidad']

#Agrupar por producto y calcular métricas
df_rendimiento = df_ventas.groupby('producto', as_index=False).agg({
    'cantidad': 'sum',
    'total_venta': 'sum'
})

#Calcular el promedio de ventas para definir "alto rendimiento"
promedio_ventas = df_rendimiento['total_venta'].mean()

#Filtrar productos que superen el promedio
df_alto_rendimiento = df_rendimiento[df_rendimiento['total_venta'] > promedio_ventas]

# Ordenar de mayor a menor
df_alto_rendimiento = df_alto_rendimiento.sort_values(by='total_venta', ascending=False)

#Mostrar resultados
print("=== Productos de alto rendimiento ===")
print(f"Promedio de ventas es = {promedio_ventas:,.2f}")

display(df_alto_rendimiento)

#Mostrar total de ingreso de lo productos con mejores rendimientos
print(f"Total de ingresos de productos con mejores rendimientos= ${df_alto_rendimiento['total_venta'].sum():,.2f}")

=== Productos de alto rendimiento ===
Promedio de ventas es = 48,903.12


producto  cantidad  total_venta
19     Lámpara de mesa    1112.0     82276.38
3          Auriculares     958.0     74175.58
20          Microondas     912.0     72562.89
5             Cafetera     765.0     59607.31
9    Cuadro decorativo     726.0     54297.60
27          Smartphone     665.0     54132.44
25            Secadora     696.0     52115.45
16   Jarrón decorativo     672.0     51130.88
4             Batidora     672.0     50979.20
24   Rincón de plantas     691.0     50456.45
13  Freidora eléctrica     630.0     50155.15
2           Aspiradora     651.0     50085.86
15     Horno eléctrico     633.0     49913.90
18            Lavadora     671.0     48946.44

Total de ingresos de productos con mejores rendimientos= $800,835.53


###**3- Agregación: Resumir las ventas por categoría de producto y analizar los ingresos generados.**

In [216]:
#Agrupar por categoría y sumar cantidad e ingresos
df_categoria = df_ventas.groupby('categoria', as_index=False).agg({
    'cantidad': 'sum',       # total de unidades vendidas por categoría
    'total_venta': 'sum'     # ingresos totales por categoría
})

#Ordenar por ingresos descendente
df_categoria = df_categoria.sort_values(by='total_venta', ascending=False)

#Mostrar resultados
print("=== Ventas resumidas por categoría ===")
display(df_categoria)

# Mostar Total de Ingreso
print(f"Total de ingresos = ${df_categoria['total_venta'].sum():,.2f}")


=== Ventas resumidas por categoría ===


categoria  cantidad  total_venta
1  Electrodomésticos    6592.0    505299.63
2        Electrónica    6413.0    482577.80
0         Decoración    6490.0    479216.09

Total de ingresos = $1,467,093.52


#**Anexo**
####**Archivos subidos al drive para la pre entrega**
**Descripción de los Datos**
*   Set de datos.pdf

**Datos**
*   ventas.csv
*   clientes.csv
*   marketing.csv

**Archivo Colab con la pre entrega**
*   Cañete Javier Dario - Comisión 25261 - TPI Data Analytics.ipynb

**Github**

[https://github.com/JotaDC/TPI-Data-Analytics-TalentoTech](https://github.com/JotaDC/TPI-Data-Analytics-TalentoTech)




